development:
  adapter: postgresql
  encoding: utf8
  database: cdl_development
  pool: 5
  username: cdluser
  password: cdlpass

test: &TEST
  adapter: postgresql
  encoding: utf8
  database: cdl_test
  pool: 5
  username: cdluser
  password: cdlpass
